{{- $appid := .Values.appId -}}
apiVersion: v1
data:
  tls.crt: {{ index (index .Values .Values.appId) "tlsCrt" }}
  tls.key: {{ index (index .Values .Values.appId) "tlsKey" }}
kind: Secret
metadata:
  name: {{ lower $appid }}-tls-secret-web
type: kubernetes.io/tls
