apiVersion: v1
kind: Service
metadata:
  name: {{ include "apz-ms-appzillonbanking-kyc.fullname" . }}
  labels:
    {{- include "apz-ms-appzillonbanking-kyc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: glowroot
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    {{- include "apz-ms-appzillonbanking-kyc.selectorLabels" . | nindent 4 }}
