{{- $enviroment := .Values.enviroment -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apz-ms-appzillonbanking-kendra-application-configmap
data:
{{ ($.Files.Glob (printf "properties/application-%s.properties" $enviroment)).AsConfig | indent 2 }}
{{ ($.Files.Glob (printf "properties/database-%s.properties" $enviroment)).AsConfig | indent 2 }}
{{ ($.Files.Glob (printf "properties/logback-kendra-%s.xml" $enviroment)).AsConfig | indent 2 }}
{{ ($.Files.Glob (printf "properties/ExternalServiceURL-%s.json" $enviroment)).AsConfig | indent 2 }}