apiVersion: v1
data:
  passwd: {{ index (index .Values .Values.serverWarName) "dbPasswd" }}
  username: {{ index (index .Values .Values.serverWarName) "dbUsername" }}
kind: Secret
metadata:
  name: {{ lower .Values.secretAppTag }}-db-secret
