apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ lower .Values.secretAppTag }}-server-db-conf
data:
  driverClassName: {{ .Values.driverClassName }}
  dburlappzilloncb: {{ .Values.dburlappzilloncb }}
  dburlgrameenkoota: {{ .Values.dburlgrameenkoota }}
